services:
  pos_db:
    image: pgvector/pgvector:pg18
    container_name: library_database
    volumes:
      - postgres_data:/var/lib/postgresql/18/docker/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  migrate:
    build: .
    command: alembic upgrade head
    env_file: .env.docker
    depends_on:
      pos_db:
        condition: service_healthy
    restart: on-failure

  app:
    build: .
    ports:
      - "8000:8000"
    env_file: .env.docker
    volumes:
      - ./api:/app/api:z
      - ./core:/app/core:z
      - ./domain:/app/domain:z
      - ./infrastructure:/app/infrastructure:z
      - ./orchestrator:/app/orchestrator:z
      - ./repositories:/app/repositories:z
      - ./services:/app/services:z
      - ./uow:/app/uow:z
      - ./dependencies:/app/dependencies:z
      - ./migrations:/app/migrations:z
      - ./main.py:/app/main.py:z
      - ./alembic.ini:/app/alembic.ini:z
    command: ["sh", "-c", "fastapi run main.py --host 0.0.0.0 --port ${PORT:-8000} --reload"]
    depends_on:
      migrate:
        condition: service_completed_successfully
      pos_db:
        condition: service_healthy
      cache:
        condition: service_healthy

  cache:
    image : redis    
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG || exit 1"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

volumes:
  postgres_data:
