"""Definicion de tablas para prestmaos y solicitudes

Revision ID: 839067e0e6af
Revises: ac4824f65628
Create Date: 2026-05-28 23:03:56.129633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '839067e0e6af'
down_revision: Union[str, Sequence[str], None] = 'ac4824f65628'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitudes_libro',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_libro', sa.Integer(), nullable=False),
    sa.Column('tiempo_espera', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'NOTIFICADA', 'COMPLETADA', 'CANCELADA', name='estadosolicitud'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['id_libro'], ['libros.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prestamos',
    sa.Column('codigo_ejemplar', sa.String(length=50), nullable=False),
    sa.Column('id_usuario_asociado', sa.Integer(), nullable=False),
    sa.Column('fecha_aprobacion', sa.Date(), nullable=True),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=True),
    sa.Column('fecha_regreso', sa.Date(), nullable=True),
    sa.Column('dias_prestamo', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'CANCELADO', 'ACTIVO', 'CONCLUIDO', 'PERDIDO', 'VENCIDO', name='estadoprestamo'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.CheckConstraint('dias_prestamo < 14', name='ck_prestamos_dias_prestamo'),
    sa.ForeignKeyConstraint(['codigo_ejemplar'], ['ejemplares.codigo'], ),
    sa.ForeignKeyConstraint(['id_usuario_asociado'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prestamos')
    op.drop_table('solicitudes_libro')
    # ### end Alembic commands ###
