"""cambios a solicitudes y prestamos

Revision ID: da9e7c2e837f
Revises: 4bf7fafc5d44
Create Date: 2026-06-02 18:56:16.827485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'da9e7c2e837f'
down_revision: Union[str, Sequence[str], None] = '4bf7fafc5d44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prestamos', sa.Column('solicitud_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'prestamos', ['solicitud_id'])
    op.create_foreign_key(None, 'prestamos', 'solicitudes_libro', ['solicitud_id'], ['id'])
    op.drop_column('prestamos', 'dias_prestamo')
    op.add_column('solicitudes_libro', sa.Column('codigo_ejemplar', sa.String(length=50), nullable=False))
    op.add_column('solicitudes_libro', sa.Column('tiempo_prestamo', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'solicitudes_libro', 'ejemplares', ['codigo_ejemplar'], ['codigo'])
    op.create_check_constraint('ck_tiempo_prestamo', 'solicitudes_libro', 'tiempo_prestamo < 15')
    op.create_check_constraint('ck_tiempo_espera', 'solicitudes_libro', 'tiempo_espera < 8')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_tiempo_prestamo', 'solicitudes_libro', type_='check')
    op.drop_constraint('ck_tiempo_espera', 'solicitudes_libro', type_='check')
    op.drop_constraint(None, 'solicitudes_libro', type_='foreignkey')
    op.drop_column('solicitudes_libro', 'tiempo_prestamo')
    op.drop_column('solicitudes_libro', 'codigo_ejemplar')
    op.add_column('prestamos', sa.Column('dias_prestamo', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'prestamos', type_='foreignkey')
    op.drop_constraint(None, 'prestamos', type_='unique')
    op.drop_column('prestamos', 'solicitud_id')
    # ### end Alembic commands ###
