"""Initial setup

Revision ID: 84968ccab868
Revises:
Create Date: 2026-06-28 22:14:51.094729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '84968ccab868'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('autores',
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generos',
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('libros',
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('isbn', sa.String(length=13), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('editorial', sa.String(length=100), nullable=True),
    sa.Column('fecha_publicacion', sa.Date(), nullable=True),
    sa.Column('url_portada', sa.String(length=500), nullable=True),
    sa.Column('lenguaje', sa.String(length=2), nullable=False),
    sa.Column('num_paginas', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isbn')
    )
    op.create_table('usuarios',
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('numero_contacto', sa.String(length=9), nullable=False),
    sa.Column('rol', sa.Enum('BIBLIOTECARIO', 'LECTOR', name='userrole'), nullable=False),
    sa.Column('hash_contrasena', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('ejemplares',
    sa.Column('libro_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('estado', sa.Enum('DISPONIBLE', 'PRESTADO', 'DANADO', name='bookcopystatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['libro_id'], ['libros.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('libro_autores',
    sa.Column('libro_id', sa.Integer(), nullable=False),
    sa.Column('autor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['autor_id'], ['autores.id'], ),
    sa.ForeignKeyConstraint(['libro_id'], ['libros.id'], ),
    sa.PrimaryKeyConstraint('libro_id', 'autor_id')
    )
    op.create_table('libro_embeddings',
    sa.Column('id_libro', sa.Integer(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['id_libro'], ['libros.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_libro_embeddings_hnsw', 'libro_embeddings', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_table('libro_generos',
    sa.Column('libro_id', sa.Integer(), nullable=False),
    sa.Column('genero_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genero_id'], ['generos.id'], ),
    sa.ForeignKeyConstraint(['libro_id'], ['libros.id'], ),
    sa.PrimaryKeyConstraint('libro_id', 'genero_id')
    )
    op.create_table('solicitudes_libro',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_libro', sa.Integer(), nullable=False),
    sa.Column('codigo_ejemplar', sa.String(length=50), nullable=True),
    sa.Column('tiempo_espera', sa.Integer(), nullable=False),
    sa.Column('tiempo_prestamo', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'CANCELADA', 'ASIGNADA', 'NOTIFICADA', 'COMPLETADA', name='loanrequeststatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.CheckConstraint('tiempo_espera < 8', name='ck_tiempo_espera'),
    sa.CheckConstraint('tiempo_prestamo < 15', name='ck_tiempo_prestamo'),
    sa.ForeignKeyConstraint(['codigo_ejemplar'], ['ejemplares.codigo'], ),
    sa.ForeignKeyConstraint(['id_libro'], ['libros.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prestamos',
    sa.Column('codigo_ejemplar', sa.String(length=50), nullable=False),
    sa.Column('id_usuario_asociado', sa.Integer(), nullable=False),
    sa.Column('fecha_aprobacion', sa.Date(), nullable=False),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=False),
    sa.Column('fecha_regreso', sa.Date(), nullable=True),
    sa.Column('estado', sa.Enum('PENDIENTE', 'CANCELADO', 'ACTIVO', 'CONCLUIDO', 'PERDIDO', 'VENCIDO', name='loanstatus'), nullable=False),
    sa.Column('solicitud_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['codigo_ejemplar'], ['ejemplares.codigo'], ),
    sa.ForeignKeyConstraint(['id_usuario_asociado'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['solicitud_id'], ['solicitudes_libro.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('solicitud_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prestamos')
    op.drop_table('solicitudes_libro')
    op.drop_table('libro_generos')
    op.drop_index('ix_libro_embeddings_hnsw', table_name='libro_embeddings', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('libro_embeddings')
    op.drop_table('libro_autores')
    op.drop_table('ejemplares')
    op.drop_table('usuarios')
    op.drop_table('libros')
    op.drop_table('generos')
    op.drop_table('autores')
    # ### end Alembic commands ###
