"""modified prestamo, solicitud_prestamo book_copy fields

Revision ID: 84d1f26834dc
Revises: 4b7bdc7883c4
Create Date: 2026-07-03 19:25:57.379486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84d1f26834dc'
down_revision: Union[str, Sequence[str], None] = '4b7bdc7883c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prestamos', sa.Column('id_ejemplar', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('prestamos_codigo_ejemplar_fkey'), 'prestamos', type_='foreignkey')
    op.create_foreign_key(None, 'prestamos', 'ejemplares', ['id_ejemplar'], ['id'])
    op.drop_column('prestamos', 'codigo_ejemplar')
    op.add_column('solicitudes_libro', sa.Column('id_ejemplar', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('solicitudes_libro_codigo_ejemplar_fkey'), 'solicitudes_libro', type_='foreignkey')
    op.create_foreign_key(None, 'solicitudes_libro', 'ejemplares', ['id_ejemplar'], ['id'])
    op.drop_column('solicitudes_libro', 'codigo_ejemplar')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solicitudes_libro', sa.Column('codigo_ejemplar', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'solicitudes_libro', type_='foreignkey')
    op.create_foreign_key(op.f('solicitudes_libro_codigo_ejemplar_fkey'), 'solicitudes_libro', 'ejemplares', ['codigo_ejemplar'], ['codigo'])
    op.drop_column('solicitudes_libro', 'id_ejemplar')
    op.add_column('prestamos', sa.Column('codigo_ejemplar', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'prestamos', type_='foreignkey')
    op.create_foreign_key(op.f('prestamos_codigo_ejemplar_fkey'), 'prestamos', 'ejemplares', ['codigo_ejemplar'], ['codigo'])
    op.drop_column('prestamos', 'id_ejemplar')
    # ### end Alembic commands ###
