"""Add soft delete to books

Revision ID: 9fe1781235c3
Revises: 84968ccab868
Create Date: 2026-06-29 01:28:51.348011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fe1781235c3'
down_revision: Union[str, Sequence[str], None] = '84968ccab868'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ejemplares', sa.Column('activo', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.add_column('libros', sa.Column('activo', sa.Boolean(), nullable=False, server_default=sa.true()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('libros', 'activo')
    op.drop_column('ejemplares', 'activo')
    # ### end Alembic commands ###
