"""test

Revision ID: ddcd690a0f49
Revises: 530f7192dfa3
Create Date: 2026-06-27 20:22:13.473635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddcd690a0f49'
down_revision: Union[str, Sequence[str], None] = '530f7192dfa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prestamos', sa.Column('id_solicitud', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'prestamos', ['id_solicitud'])
    op.create_foreign_key(None, 'prestamos', 'solicitudes_libro', ['id_solicitud'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'prestamos', type_='foreignkey')
    op.drop_constraint(None, 'prestamos', type_='unique')
    op.drop_column('prestamos', 'id_solicitud')
    # ### end Alembic commands ###
